services:
  - type: web
    name: carbon-components-svelte-v11
    env: static
    buildCommand: cd docs; yarn; yarn build
    staticPublishPath: docs/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
